[Settings]
FnSuperSwap=false
UsbPowerShare=false
UserMode=performance_mode
fan1SpeedSettings=0|30|45|55|70|90|115
fan1TempSettings=55|65|75|80|85|90
fan2SpeedSettings=0|30|45|55|70|90|115
fan2TempSettings=55|65|75|80|85|90
fanModeAdvanced=true
