[Settings]
FnSuperSwap=false
UsbPowerShare=false
UserMode=performance_mode
fan1SpeedSettings=0|43|45|54|60|90|100
fan1TempSettings=55|64|73|76|80|85
fan2SpeedSettings=0|43|48|54|60|90|100
fan2TempSettings=55|61|67|73|80|85
fanModeAdvanced=false
