general {
   hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 2
}

label { 
    text = $TIME
    font_size = 100
    font_family = Noto Sans Mono

    halign = center
    valign = center
    position = 0, 100

    color = rgba(ffa500ff)
    shadow_passes = 3
    shadow_size = 5
}

label {
    text = $USER
    font_size = 20
    font_family = Noto Sans Mono

    halign = center
    valign = center
    position = 0, 0

    color = rgba(ffa500ff)
    shadow_passes = 2
    shadow_size = 5
}

input-field {
    monitor =
    size = 10%, 5%
    outline_thickness = 2
    dots_size = 0.2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(ffa500ff)
    check_color = rgba(990099ff)
    fail_color = rgba(ff0000ff)

    font_color = rgba(ffffffff)
    placeholder_text = <i>Password</i>
    rounding = 10

    halign = center
    valign = center
    position = 0, -100

    shadow_passes = 3
    shadow_size = 5
}
