# --- Main Colors ---
background            #161217
foreground            #e9e0e7
cursor                #e9e0e7
cursor_text_color     #161217

selection_background  #514254
selection_foreground  #f1dcf3

url_color             #f5b7b4

# --- ANSI Colors ---
color0                #161217
# color1                #ffb4ab
color1                #93000a
color2                #f5b7b4
color3                #d5c0d7
color4                #e5b6f2
color5                #f5b7b4
color6                #d5c0d7
color7                #e9e0e7

color8                #4c444d
# color9                #93000a
color9                #ffb4ab
color10               #663b39
# color11               #514254
color11               #e5b6f2
color12               #5d386b
color13               #514254
color14               #663b39
color15               #cec3cd

# # --- Starship Prompt Bubbles ---
# color255              #5d386b
# color254              #e5b6f2
# color253              #514254
# color252              #d5c0d7
# color251              #663b39
# color250              #f5b7b4
# color249              #93000a
# color248              #ffb4ab

# # color232              #f9d8ff
# color233              #452153
# # color234              #f1dcf3
# color235              #392c3d
# # color236              #ffdad8
# color237              #4c2524
# # color238              #ffdad6
# color239              #690005
# # color240              #f9d8ff

# # Matched with unthemed light/dark
# color243              #e5b6f2
# color244              #ffb4ab
# color245              #4c444d

# --- UI Elements ---
active_tab_foreground   #452153
active_tab_background   #e5b6f2
inactive_tab_foreground #f9d8ff
inactive_tab_background #5d386b

active_border_color     #e5b6f2
inactive_border_color   #988e97

# --- Marks ---
mark1_foreground        #2e0a3c
mark1_background        #f9d8ff
mark2_foreground        #231728
mark2_background        #f1dcf3
mark3_foreground        #331110
mark3_background        #ffdad8
